name: ci

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Log versions
        run: |
          deno --version
      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint --unstable

      - name: Run deno test
        run: deno test -A --unstable --import-map=import_map.json --coverage

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.repository, 'justjavac') && 
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true